In [33]:
import torch
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print(torch.__version__)


2.8.0+cu126


### Tensors

In [34]:
#scalar

scalar = torch.tensor(7)
scalar,scalar.ndim,scalar.dtype,scalar.shape


(tensor(7), 0, torch.int64, torch.Size([]))

In [35]:
# vector
vector = torch.tensor([7,7])
vector,vector.ndim,vector.dtype,vector.shape

(tensor([7, 7]), 1, torch.int64, torch.Size([2]))

In [36]:
#matrix
matrix = torch.tensor([[1,2],[3,4]])
matrix,matrix.ndim,matrix.dtype,matrix.shape

(tensor([[1, 2],
         [3, 4]]),
 2,
 torch.int64,
 torch.Size([2, 2]))

In [37]:
matrix[1]

tensor([3, 4])

In [38]:
# tensor
tensor = torch.tensor([[[1,2],[3,4]],
                      [[5,6],[7,8]],
                      [[10,11],[12,13]]
                      ])
tensor,tensor.ndim,tensor.shape,tensor.dtype

(tensor([[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]],
 
         [[10, 11],
          [12, 13]]]),
 3,
 torch.Size([3, 2, 2]),
 torch.int64)

In [39]:
##Random TENSORS
random_tensor = torch.rand(3,4)
random_tensor,random_tensor.ndim

(tensor([[0.0453, 0.4393, 0.1669, 0.1571],
         [0.2733, 0.2259, 0.7028, 0.8863],
         [0.5476, 0.5135, 0.0616, 0.9935]]),
 2)

In [40]:
random_image = torch.rand(size=(224,224,3))
random_image,random_image.shape,random_image.ndim

(tensor([[[0.1037, 0.8585, 0.9591],
          [0.0073, 0.4063, 0.0635],
          [0.0762, 0.6460, 0.2606],
          ...,
          [0.1435, 0.9718, 0.0338],
          [0.9560, 0.6136, 0.3650],
          [0.2551, 0.8773, 0.5568]],
 
         [[0.5244, 0.2374, 0.5457],
          [0.2868, 0.7513, 0.5084],
          [0.5376, 0.4900, 0.8219],
          ...,
          [0.5333, 0.1540, 0.2430],
          [0.5796, 0.5559, 0.9698],
          [0.5359, 0.3189, 0.7159]],
 
         [[0.3152, 0.2824, 0.1960],
          [0.9929, 0.7678, 0.1376],
          [0.6217, 0.9459, 0.8917],
          ...,
          [0.1337, 0.9369, 0.7846],
          [0.2825, 0.9179, 0.2748],
          [0.9827, 0.5601, 0.8307]],
 
         ...,
 
         [[0.1036, 0.2600, 0.6769],
          [0.5431, 0.6527, 0.2987],
          [0.4946, 0.0656, 0.5750],
          ...,
          [0.6068, 0.9333, 0.6955],
          [0.9015, 0.8417, 0.3549],
          [0.2149, 0.7576, 0.8626]],
 
         [[0.7228, 0.5188, 0.9860],
          [0

In [41]:
### Creating tenosr with zeros and ones
T = torch.ones(size=(3,4))
T,T.dtype,T.ndim,T.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [42]:
O = torch.zeros(size=(3,4))
O,O.dtype,O.ndim,O.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [43]:
#### Creating a range of Tensors
one_to_ten = torch.arange(1,11)
one_to_ten,one_to_ten.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [44]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros,ten_zeros.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([10]))

# Datatypes


In [50]:
#Float_32
float_32_tensor = torch.tensor([3.0,6.0,4.0],
                               dtype=None,
                               device="cpu",
                               requires_grad=True)
float_32_tensor,float_32_tensor.dtype,float_32_tensor.shape

(tensor([3., 6., 4.], requires_grad=True), torch.float32, torch.Size([3]))

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor,float_16_tensor.dtype

(tensor([3., 6., 4.], dtype=torch.float16, grad_fn=<ToCopyBackward0>),
 torch.float16)

In [53]:
float_32_tensor.device

device(type='cpu')

# Manupilating Tensors


In [95]:
#operations
tensor_1 =torch.rand((3,4))
tensor_2 =torch.rand((4,5))

tensor_1,tensor_2

(tensor([[0.3709, 0.3296, 0.3717, 0.6092],
         [0.6212, 0.8254, 0.8946, 0.7449],
         [0.7040, 0.8248, 0.3264, 0.9967]]),
 tensor([[0.5986, 0.0547, 0.9688, 0.3249, 0.9975],
         [0.5986, 0.7696, 0.4012, 0.0480, 0.8515],
         [0.3114, 0.3998, 0.9334, 0.8506, 0.3672],
         [0.8777, 0.4814, 0.4786, 0.5751, 0.2430]]))

In [98]:
#matrix Multiplication
tensor_matrix = torch.matmul(tensor_1,tensor_2)
tensor_matrix,tensor_matrix.shape

(tensor([[1.0697, 0.7158, 1.1301, 0.8028, 0.9352],
         [1.7983, 1.3854, 2.1245, 1.4308, 1.8320],
         [1.8915, 1.2835, 1.7946, 1.1192, 1.7666]]),
 torch.Size([3, 5]))

In [96]:
#Transpose
tensor_3 = tensor_2.T
tensor_4 = torch.transpose(tensor_2,0,1)
tensor_3,tensor_4
#torch.matmul(tensor_1,torch.transpose(tensor_2,0,1))

(tensor([[0.5986, 0.5986, 0.3114, 0.8777],
         [0.0547, 0.7696, 0.3998, 0.4814],
         [0.9688, 0.4012, 0.9334, 0.4786],
         [0.3249, 0.0480, 0.8506, 0.5751],
         [0.9975, 0.8515, 0.3672, 0.2430]]),
 tensor([[0.5986, 0.5986, 0.3114, 0.8777],
         [0.0547, 0.7696, 0.3998, 0.4814],
         [0.9688, 0.4012, 0.9334, 0.4786],
         [0.3249, 0.0480, 0.8506, 0.5751],
         [0.9975, 0.8515, 0.3672, 0.2430]]))

In [69]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [70]:
#Multiplication
tensor*10,torch.mul(tensor,10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [139]:
#Aggregations
tensor = torch.arange(1,25,dtype=torch.float32)
tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [140]:
tensor.min(),tensor.max(),tensor.mean(), tensor.sum()

(tensor(1.), tensor(24.), tensor(12.5000), tensor(300.))

In [135]:
#Positional min and max
x =  torch.arange(0,50,10)
x,x.argmin(),x.argmax() #At what index the min and max values are at

(tensor([ 0, 10, 20, 30, 40]), tensor(0), tensor(4))

# Reshapping,stacking,squeezing and unsqueezing tensor

In [172]:
k = torch.arange(1,10)
k,k.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [173]:
#Reshape
k_reshaped = k.reshape(1,9)
k_reshaped,k_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [174]:
#view
z = k.view(1,9) #this is the view of k tensor
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [175]:
z[:,0]=5 #if we change the value in the view then the value in original tensor also changes because it keeps same memory.

In [176]:
k

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
#stacking
k_stacked = torch.stack([k,k,k,k],dim=0)
k_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [178]:
#Squeeze
k.shape,k_reshaped.shape

(torch.Size([9]), torch.Size([1, 9]))

In [179]:
k_squeezed = k_reshaped.squeeze()
k_squeezed,k_squeezed.shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [181]:
l = k.squeeze()
l,l.shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [183]:
#unsqueeze
m = k_reshaped.unsqueeze(dim=0)
m,m.shape

(tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]]), torch.Size([1, 1, 9]))

In [188]:
#permute
a = torch.rand(size = (224,224,3))
a_permuted = a.permute(2,1,0)
a.shape,a_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing



In [196]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape,x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [199]:
x[0,0,:]


tensor([1, 2, 3])

In [215]:
x[0,1,0]

tensor(4)

In [219]:
x[:,:,2]

tensor([[3, 6, 9]])

In [220]:
x[0,:,2]

tensor([3, 6, 9])

In [221]:
x[0,0,2]

tensor(3)

In [218]:
x[0,2,2]

tensor(9)

# pytorch and Numpy

In [257]:
# numpy to tensor
data = np.arange(1.0,8.0)
tensor = torch.from_numpy(data)
tensor,tensor.dtype
data,tensor,tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [258]:
data = data+1
data,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [262]:
# tensor to numpy
tensor = torch.ones(7)
numpy_one = tensor.numpy()
tensor,numpy_one.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]), dtype('float32'))

# Reproducbility


In [266]:
#random seed

random_seed = 42
torch.manual_seed(random_seed)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_b = torch.rand(3,4)

random_tensor_A,random_tensor_b,print(random_tensor_A==random_tensor_b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 None)

In [3]:
#GPU
import torch
torch.cuda.is_available()

True

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
#creating a tensor on cpu
tensor = torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [8]:
#move the tensor to GPU
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [13]:
tensor_og = tensor_gpu.cpu().numpy()
tensor_og

array([1, 2, 3])