 ### Introduction to tensors



In [1]:
import tensorflow as tf
print(tf.__version__)

2.19.0


### creating tensors with `tf.constant()`

In [2]:
# creating tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the no of dimensions of a tensor
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
vector1 = tf.constant([10,10,20])
vector1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 20], dtype=int32)>

In [7]:
vector1.ndim

1

In [8]:
# create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim


2

In [10]:
matrix2 = tf.constant([[10.,7.],
                       [3.,2.],
                       [8.,9.]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
matrix2.ndim

2

In [12]:
tensor = tf.constant([[[1,2],[2,3]],
                     [[4,5],[5,4]],
                     [[7,8],[8,7]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [5, 4]],

       [[7, 8],
        [8, 7]]], dtype=int32)>

In [13]:
tensor.ndim

3

### Creating tensors with `tf.variable()`


In [14]:
tensor_var = tf.Variable([10,7])
tensor_const = tf.constant([10,7])
tensor_var,tensor_const

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
tensor_var[0].assign(7)
tensor_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# tensor_const[0].assign(7)
# tensor_const             # here in creating the tensor if we use tf.constant then we cannot use assign to change the element
                          # where as in tf.variable we can change it

## Creating `random tensors`

In [17]:
random_1 = tf.random.Generator.from_seed(1)
random_1.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.43842274, -0.53439844],
       [-0.07710262,  1.5658046 ],
       [-0.1012345 , -0.2744976 ]], dtype=float32)>

In [18]:
random_2 = tf.random.Generator.from_seed(50)
k = random_2.normal(shape=(5,3,2))
print(k)
k.ndim

tf.Tensor(
[[[ 0.45331386  1.1487608 ]
  [-1.2659091  -0.47450137]
  [ 2.006022    0.28288034]]

 [[-0.30288252 -1.443651  ]
  [ 1.0034493   0.20857747]
  [ 0.35700995  1.0648885 ]]

 [[ 1.2432485  -2.2173238 ]
  [ 0.18706243  0.6617961 ]
  [ 0.01380118 -0.24827152]]

 [[ 1.2111493  -0.7199124 ]
  [-0.04082382  2.6791053 ]
  [ 1.0914806   0.33149615]]

 [[-0.67958915  0.44723678]
  [-0.17811584  0.24882518]
  [ 0.49689844  0.8259971 ]]], shape=(5, 3, 2), dtype=float32)


3

In [19]:
random_2.uniform(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.9145144 , 0.49411607],
       [0.16206348, 0.5434388 ],
       [0.4207785 , 0.8114866 ]], dtype=float32)>

## Shuffle the order of tensors

In [20]:
tensor = tf.constant([[10,7],
                     [1,2],
                     [8,9]])
tf.random.set_seed(42)
tensor_shuffle = tf.random.shuffle(tensor,seed = 42)
tensor_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 8,  9]], dtype=int32)>

In [21]:
tensor_1 = tf.random.Generator.from_seed(42)
k  = tensor_1.normal(shape = (3,2))
k

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
tf.random.set_seed(42)
tf.random.shuffle(k,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
tf.random.set_seed(42)
tf.random.shuffle(k)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

In [24]:
tf.random.shuffle(k,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [25]:
tf.random.shuffle(k)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

## creating tensors with numpy arrays

In [26]:
tf.ones([3,2],tf.int32) # create tensor full of 1's

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [27]:
tf.zeros([3,2])  # create tensor full of 0's

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [28]:
# convert numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)

tensor_default = tf.constant(numpy_A)
tensor = tf.constant(numpy_A , shape = (2,3,4))

numpy_A, tensor_default, tensor

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [29]:
tensor.ndim

3

In [30]:
tensor_default.ndim

1

## Getting information from tensors

In [31]:
tensor_default.shape

TensorShape([24])

In [32]:
tensor_default[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [33]:
tensor_default[5:22]

<tf.Tensor: shape=(17,), dtype=int32, numpy=
array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
      dtype=int32)>

In [34]:
tf.size(tensor_default)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [35]:
tensor.shape

TensorShape([2, 3, 4])

In [36]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [37]:
tf.size(tensor).numpy()

np.int32(24)

In [38]:
tensor[1]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [39]:
tensor.dtype

tf.int32

## Indexing tensors

In [40]:
tensor_4 = tf.zeros(shape = [2,3,4,5])
tensor_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [41]:
tensor_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [42]:
tensor_4[1:3,1:3,1:3,1:3]

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [43]:
tensor_2 = tf.constant([[10,7],
                        [3,4]])
tensor_2,tensor_2.ndim,tensor_2.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 2,
 TensorShape([2, 2]))

In [44]:
tensor_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [45]:
tensor_3 = tensor_2[...,tf.newaxis]
tensor_3,tensor_3.ndim

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>,
 3)

In [46]:
tf.expand_dims(tensor_2,axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Manipulating Tensors

In [47]:
tensor_m = tf.constant([[10,7],
                        [3,4]])
tensor_m+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [48]:
tf.subtract(tensor_m,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [49]:
# Matrix Multiplication

In [50]:
tensor_m @ tensor_m

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [51]:
tf.matmul(tensor_m,tensor_m)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [52]:
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
X.shape,Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [53]:
y = tf.reshape(Y,shape = (2,3))

In [54]:
#matrix multification
tf.matmul(X,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [55]:
Y,y,tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [56]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [57]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [58]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [59]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [60]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [61]:
tf.tensordot(X,tf.transpose(Y),axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [62]:
tf.matmul(X,tf.reshape(Y,shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [63]:
Y,tf.reshape(Y,shape=(2,3)),tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

## changing the datatype of a tensor

In [64]:
B = tf.constant([1.7,7.4],dtype = tf.float16)
B.dtype

tf.float16

In [65]:
c = tf.constant([7,10])
c.dtype

tf.int32

In [66]:
D = tf.cast(c,dtype = tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

## Aggregating tensors

In [67]:
E = tf.constant([-7,-10])
E

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [68]:
tf.abs(E)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [69]:
# creating a random tensor

F = tf.constant(np.random.randint(0,100,size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([21, 60, 40, 58, 54, 78, 27, 22, 48, 55, 93,  6, 68, 89, 45, 26, 78,
       52, 65, 17, 88, 74, 54,  9, 36,  6, 40, 70, 58, 27, 47, 69, 26, 72,
       38, 41, 70, 66, 55, 48, 99, 74, 26, 20, 67, 28,  3, 73, 66, 41])>

In [70]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [71]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [72]:
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [73]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2493>

In [74]:
import tensorflow_probability as tfp

In [75]:
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=583>

In [76]:
tf.math.reduce_std(tf.cast(F,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=24.150371551513672>

In [77]:
tf.math.reduce_variance(tf.cast(F,dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=583.2404174804688>

In [78]:
# Find the positional max and min

tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [79]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [80]:
F[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [81]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [82]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [83]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [84]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [85]:
G = tf.constant(tf.random.uniform(shape = [50]),shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
          0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
          0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
          0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
          0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
          0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
          0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
          0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
          0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
          0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]],
      dtype=float32)>

In [86]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

## One Hot Encoding

In [91]:
color = ['red','Green','blue']
indices = [0,1,2]
depth = 3
tf.one_hot(indices,depth)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

## Math operations

In [92]:
# tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [93]:
#square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [94]:
#square root
tf.sqrt(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [100]:
# Log of H
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors with numpy

In [110]:
# creating tensor directly using numpy array
j = tf.constant(np.array([3.,7.,10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [112]:
# convert tensor into numpy array
j.numpy(), np.array(j), type(j.numpy())

(array([ 3.,  7., 10.]), array([ 3.,  7., 10.]), numpy.ndarray)

In [113]:
j.numpy()[0]

np.float64(3.0)