In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [6]:
X,y = load_iris(return_X_y = True)

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [12]:
Scaled = StandardScaler()

Scaled_X_train = Scaled.fit_transform(X_train)
Scaled_X_test = Scaled.transform(X_test)

In [13]:
Scaled_X_train

array([[ 0.29780467, -0.38230433,  0.48311318,  0.43931099],
       [ 0.42319611, -0.15631162,  0.71068367,  0.82789074],
       [ 0.79937042,  0.29567379,  0.48311318,  0.43931099],
       [ 0.04702179, -0.83428975,  0.82446891,  0.95741732],
       [-0.07836965, -0.38230433,  0.31243532,  0.18025783],
       [ 0.17241323, -0.15631162,  0.82446891,  0.82789074],
       [ 0.42319611, -0.60829704,  0.59689843,  0.05073124],
       [-0.20376109, -0.15631162,  0.48311318,  0.43931099],
       [ 2.42945913, -0.60829704,  1.73475086,  1.0869439 ],
       [ 0.92476186, -0.60829704,  0.5400058 ,  0.43931099],
       [-0.70532684,  0.97365192, -1.22366548, -1.24453458],
       [-1.70845835,  0.29567379, -1.33745072, -1.24453458],
       [-1.08150116,  1.19964463, -1.2805581 , -1.37406116],
       [-0.07836965, -0.60829704,  0.25554269,  0.18025783],
       [-0.70532684, -0.83428975,  0.14175745,  0.30978441],
       [-1.2068926 ,  0.06968109, -1.16677285, -1.24453458],
       [-1.08150116,  0.

In [15]:
import numpy as np

(X_train - np.mean(X_train , axis = 0))/np.std(X_train,axis = 0)

array([[ 0.29780467, -0.38230433,  0.48311318,  0.43931099],
       [ 0.42319611, -0.15631162,  0.71068367,  0.82789074],
       [ 0.79937042,  0.29567379,  0.48311318,  0.43931099],
       [ 0.04702179, -0.83428975,  0.82446891,  0.95741732],
       [-0.07836965, -0.38230433,  0.31243532,  0.18025783],
       [ 0.17241323, -0.15631162,  0.82446891,  0.82789074],
       [ 0.42319611, -0.60829704,  0.59689843,  0.05073124],
       [-0.20376109, -0.15631162,  0.48311318,  0.43931099],
       [ 2.42945913, -0.60829704,  1.73475086,  1.0869439 ],
       [ 0.92476186, -0.60829704,  0.5400058 ,  0.43931099],
       [-0.70532684,  0.97365192, -1.22366548, -1.24453458],
       [-1.70845835,  0.29567379, -1.33745072, -1.24453458],
       [-1.08150116,  1.19964463, -1.2805581 , -1.37406116],
       [-0.07836965, -0.60829704,  0.25554269,  0.18025783],
       [-0.70532684, -0.83428975,  0.14175745,  0.30978441],
       [-1.2068926 ,  0.06968109, -1.16677285, -1.24453458],
       [-1.08150116,  0.

In [16]:
from sklearn.preprocessing import MinMaxScaler

scale = MinMaxScaler()

scale_X_train = scale.fit_transform(X_train)
scale_X_test = scale.transform(X_test)

In [21]:
scale_X_train

array([[0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.44444444, 0.41666667, 0.69491525, 0.70833333],
       [0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.94444444, 0.33333333, 0.96610169, 0.79166667],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.16666667, 0.66666667, 0.06779661, 0.        ],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.13888889, 0.45833333, 0.10169492, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     ,

In [19]:
import numpy as np

(X_train - np.min(X_train,axis = 0))/(np.max(X_train,axis=0) - np.min(X_train,axis = 0))


array([[0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.44444444, 0.41666667, 0.69491525, 0.70833333],
       [0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.94444444, 0.33333333, 0.96610169, 0.79166667],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.16666667, 0.66666667, 0.06779661, 0.        ],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.13888889, 0.45833333, 0.10169492, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     ,

In [22]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [26]:
data = fetch_openml('car',as_frame = True).frame

c:\Users\kumar\Desktop\Libraries\.venv\Lib\site-packages\sklearn\datasets\_openml.py:324: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)


In [27]:
data

buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

In [29]:
columns_to_encode = ['lug_boot','safety']

encoder = OrdinalEncoder(
    categories = [
        ['small','med','big'],
        ['low','med','high']
    ]
)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [30]:
data

buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [62]:
data.lug_boot.value_counts()

lug_boot
0.0    576
1.0    576
2.0    576
Name: count, dtype: int64

In [31]:
 encoder.inverse_transform(data[columns_to_encode])

array([['small', 'low'],
       ['small', 'med'],
       ['small', 'high'],
       ...,
       ['big', 'low'],
       ['big', 'med'],
       ['big', 'high']], shape=(1728, 2), dtype=object)

## OneHotEncoder

In [34]:
df = fetch_openml('adult',as_frame = True).frame

c:\Users\kumar\Desktop\Libraries\.venv\Lib\site-packages\sklearn\datasets\_openml.py:324: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)


In [38]:
df

age         workclass  fnlwgt  education  education-num      marital-status         occupation  ...                race     sex capitalgain capitalloss hoursperweek native-country  class
0       2         State-gov   77516  Bachelors             13       Never-married       Adm-clerical  ...               White    Male           1           0            2  United-States  <=50K
1       3  Self-emp-not-inc   83311  Bachelors             13  Married-civ-spouse    Exec-managerial  ...               White    Male           0           0            0  United-States  <=50K
2       2           Private  215646    HS-grad              9            Divorced  Handlers-cleaners  ...               White    Male           0           0            2  United-States  <=50K
3       3           Private  234721       11th              7  Married-civ-spouse  Handlers-cleaners  ...               Black    Male           0           0            2  United-States  <=50K
4       1           Private  338409  Bachelors             13  Married-civ-spouse     Prof-specialty  ...               Black  Female           0           0            2           Cuba  <=50K
...    ..               ...     ...        ...            ...                 ...                ...  ...                 ...     ...         ...         ...          ...            ...    ...
48837   2           Private  215419  Bachelors             13            Divorced     Prof-specialty  ...               White  Female           0           0            2  United-States  <=50K
48838   4               NaN  321403    HS-grad              9             Widowed                NaN  ...               Black    Male           0           0            2  United-States  <=50K
48839   2           Private  374983  Bachelors             13  Married-civ-spouse     Prof-specialty  ...               White    Male           0           0            3  United-States  <=50K
48840   2           Private   83891  Bachelors             13            Divorced       Adm-clerical  ...  Asian-Pac-Islander    Male           2           0            2  United-States  <=50K
48841   1      Self-emp-inc  182148  Bachelors             13  Married-civ-spouse    Exec-managerial  ...               White    Male           0           0            3  United-States   >50K

[48842 rows x 15 columns]

In [44]:
df.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [45]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [48]:
encode = OneHotEncoder(handle_unknown='ignore',sparse_output = False)

encoded_values = encode.fit_transform(df[['occupation','race']])
new_columns = encode.get_feature_names_out(['occupation','race'])

In [49]:
encoded_values

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(48842, 20))

In [51]:
new_columns

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [60]:
df_encoded = pd.DataFrame(encoded_values,columns = new_columns,index  = df.index)

df_final = pd.concat(
    [df.drop(columns = ['occupation','race']),df_encoded], axis = 1
)

In [61]:
df_final

age         workclass  fnlwgt  education  education-num      marital-status  ... occupation_nan race_Amer-Indian-Eskimo race_Asian-Pac-Islander race_Black race_Other race_White
0       2         State-gov   77516  Bachelors             13       Never-married  ...            0.0                     0.0                     0.0        0.0        0.0        1.0
1       3  Self-emp-not-inc   83311  Bachelors             13  Married-civ-spouse  ...            0.0                     0.0                     0.0        0.0        0.0        1.0
2       2           Private  215646    HS-grad              9            Divorced  ...            0.0                     0.0                     0.0        0.0        0.0        1.0
3       3           Private  234721       11th              7  Married-civ-spouse  ...            0.0                     0.0                     0.0        1.0        0.0        0.0
4       1           Private  338409  Bachelors             13  Married-civ-spouse  ...            0.0                     0.0                     0.0        1.0        0.0        0.0
...    ..               ...     ...        ...            ...                 ...  ...            ...                     ...                     ...        ...        ...        ...
48837   2           Private  215419  Bachelors             13            Divorced  ...            0.0                     0.0                     0.0        0.0        0.0        1.0
48838   4               NaN  321403    HS-grad              9             Widowed  ...            1.0                     0.0                     0.0        1.0        0.0        0.0
48839   2           Private  374983  Bachelors             13  Married-civ-spouse  ...            0.0                     0.0                     0.0        0.0        0.0        1.0
48840   2           Private   83891  Bachelors             13            Divorced  ...            0.0                     0.0                     1.0        0.0        0.0        0.0
48841   1      Self-emp-inc  182148  Bachelors             13  Married-civ-spouse  ...            0.0                     0.0                     0.0        0.0        0.0        1.0

[48842 rows x 33 columns]